### ISSUE TITLE
voliso error Illegal division by zero NumericUtilities.pm

### ISSUE THREAD

**Issue by SaibotMagd** [BIC-MNI/minc-toolkit-v2#138]
### Summary
I don't understand the error message.
I'm neither a programmer nor linux expert so I can't even say if the problem comes from nipype, minc-toolkit or volgenmodel itself. Sorry if I guessed wrong.

```
{'node': _preprocess_voliso3,
 'traceback': ['Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__\n    mp_context=mp_context,\n',
  "TypeError: __init__() got an unexpected keyword argument 'initializer'\n",
  '\nDuring handling of the above exception, another exception occurred:\n\n',
  'Traceback (most recent call last):\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node\n    result["result"] = node.run(updatehash=updatehash)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run\n    result = self._run_interface(execute=True)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface\n    return self._run_command(execute)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command\n    result = self._interface.run(cwd=outdir)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 397, in run\n    runtime = self._run_interface(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface\n    self.raise_exception(runtime)\n',
  '  File "/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception\n    ).format(**runtime.dictcopy())\n',
  'RuntimeError: Command:\nvoliso --avgstep --clobber /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_mouse_6_volcentre_norm_volpad.mnc gerbil_mouse_6_volcentre_norm_volpad_voliso.mnc\nStandard output:\n\nStandard error:\n
Illegal division by zero at /home/nistmni/src/minc-toolkit-v2/mni-perllib/MNI/NumericUtilities.pm (autosplit into /home/nistmni/src/build/minc-toolkit-v2/mni-perllib/perl/auto/MNI/NumericUtilities/round.al) line 198.\n
Died at /home/saibotmagd/toolboxes/minc/1.9.18/bin/voliso line 112.\nReturn code: 255\n']}
```

### Actual behavior
Pipeline (https://github.com/carlohamalainen/volgenmodel-nipype) fails.
### Expected behavior
I don't know what the function 'voliso' does but the volgenmodel pipeline runs successfully with the official sample data.
### How to replicate the behavior
Maybe I have to upload the image files?
### Script/Workflow details
It's probably an error regarding the input file. Here the output from nii2mnc:

```
<nifti_image
  nifti_type = 'NIFTI-1+'
  header_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_filename = '/home/saibotmagd/srcImageData/Template_Creation/5543_rigReg_rH.nii'
  image_offset = '352'
  ndim = '3'
  nx = '678'
  ny = '819'
  nz = '448'
  dx = '1'
  dy = '1'
  dz = '1'
  datatype = '4'
  datatype_name = 'INT16'
  nvox = '248766336'
  nbyper = '2'
  byteorder = 'LSB_FIRST'
  scl_slope = '1'
  scl_inter = '0'
  xyz_units = '2'
  xyz_units_name = 'mm'
  qform_code = '2'
  qform_code_name = 'Aligned Anat'
  qto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  qto_ijk_matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  quatern_b = '0'
  quatern_c = '0'
  quatern_d = '1'
  qoffset_x = '-0'
  qoffset_y = '-0'
  qoffset_z = '0'
  qfac = '1'
  qform_i_orientation = 'Right-to-Left'
  qform_j_orientation = 'Anterior-to-Posterior'
  qform_k_orientation = 'Inferior-to-Superior'
  sform_code = '1'
  sform_code_name = 'Scanner Anat'
  sto_xyz_matrix = '-1 0 0 -0 0 -1 0 -0 0 0 1 0 0 0 0 1'
  sto_ijk matrix = '-1 0 0 0 0 -1 0 0 0 0 1 0 0 0 0 1'
  sform_i_orientation = 'Right-to-Left'
  sform_j_orientation = 'Anterior-to-Posterior'
  sform_k_orientation = 'Inferior-to-Superior'
  num_ext = '0'
/>
Using s-form transform:
 -1.0000,   0.0000,   0.0000,  -0.0000, 
  0.0000,  -1.0000,   0.0000,  -0.0000, 
  0.0000,   0.0000,   1.0000,   0.0000, 
  0.0000,   0.0000,   0.0000,   1.0000, 
xspace start:  -0.0000 step:  -1.0000 cosines:   1.0000  -0.0000  -0.0000 flip: 0
yspace start:  -0.0000 step:  -1.0000 cosines:  -0.0000   1.0000  -0.0000 flip: 0
zspace start:   0.0000 step:   1.0000 cosines:   0.0000   0.0000   1.0000 flip: 0
```

### Platform details:

```
210729-11:48:57,947 nipype.utils INFO:
	 Running nipype version 1.4.2 (latest: 1.5.1)
{'commit_hash': '%h',
 'commit_source': 'archive substitution',
 'networkx_version': '2.5.1',
 'nibabel_version': '3.2.1',
 'nipype_version': '1.4.2',
 'numpy_version': '1.19.5',
 'pkg_path': '/home/saibotmagd/anaconda3/envs/py34/lib/python3.6/site-packages/nipype',
 'scipy_version': '1.5.3',
 'sys_executable': '/home/saibotmagd/anaconda3/envs/py34/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.13 | packaged by conda-forge | (default, Feb 19 2021, '
                '05:36:01) \n'
                '[GCC 9.3.0]',
 'traits_version': '6.2.0'}

```

### Execution environment

Anaconda 3 env with python 3.5

**Comment by gdevenyi** [comment]
Can you please run the `voliso` command manually on the file with ``--verbose`` to see the exact set of commands.

**Comment by SaibotMagd** [comment]
> Can you please run the `voliso` command manually on the file with `--verbose` to see the exact set of commands.

This sounds like a pretty good idea. Here is the output:

```
+++ Input steps: [-1, -1, 1] +++
+++ Resulting steps: [0, 0, -0.33]  (minstep: 0) (maxstep: -0.33) +++
+++ Target ISO step: 0 +++
autocrop -clobber -short -isostep 0 /home/saibotmagd/toolboxes/volgenmodel-nipype/workflow_temp_workflowMultiProc2/preprocess_volpad/mapflow/_preprocess_volpad3/gerbil_4_mouse_volcentre_norm_volpad.mnc gerbil_4_mouse_volcentre_norm_volpad_voliso.mnc
Illegal division by zero at /home/nistmni/src/minc-toolkit-v2/mni-perllib/MNI/NumericUtilities.pm (autosplit into /home/nistmni/src/build/minc-toolkit-v2/mni-perllib/perl/auto/MNI/NumericUtilities/round.al) line 198.
Died at /home/saibotmagd/toolboxes/minc/1.9.18/bin/voliso line 112.
```

**Comment by gdevenyi** [comment]
Thanks, can you please add `-fake` to the `voliso` command so we can see what its doing computation-wise, as well as `mincinfo` on the input file. Thanks.

**Comment by vfonov** [comment]
it's trying to create a file with zero step size:
`
+++ Resulting steps: [0, 0, -0.33]  (minstep: 0) (maxstep: -0.33) +++
+++ Target ISO step: 0 +++
`

**Comment by vfonov** [comment]
`voliso` doesn't handle negative steps: https://github.com/BIC-MNI/minc-widgets/blob/master/voliso/voliso#L80

**Comment by andrewjanke** [comment]
oops...

I recall doing this to all input files in directories that did things with volgenmodel things

  # convert everything to +zyx dimension order
   mincreshape \
      -clobber \
      -2 \
      +direction \
      -dimorder zspace,yspace,xspace \
      -dimsize xspace=-1 \
      -dimsize yspace=-1 \
      -dimsize zspace=-1 \
      $in $out

I accept this was a dirty hack and probably should have spent the time figuring out all the bits of code where -ve steps did the wrong thing. I recall spending some time on this and then giving up as I'm sure there will be more problems than just this one in voliso.

**Comment by SaibotMagd** [comment]
> I accept this was a dirty hack and probably should have spent the time figuring out all the bits of code where -ve steps did the wrong thing. I recall spending some time on this and then giving up as I'm sure there will be more problems than just this one in voliso.

I don't know what the command does or why you called it "dirty", but it worked. The pipeline runs and the result is pretty amazing! Thank you a lot @andrewjanke I think you know I used your volgenmodel-pipeline.
